# Generated by Django 5.0.6 on 2024-06-26 09:19

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0002_remove_idechome_header_image_alter_idechome_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idechome',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('slider', wagtail.blocks.StreamBlock([('slide', wagtail.blocks.StructBlock([('is_first', wagtail.blocks.BooleanBlock()), ('text', wagtail.blocks.RichTextBlock()), ('dachedText', wagtail.blocks.RichTextBlock()), ('buttonText', wagtail.blocks.RichTextBlock()), ('buttonUrl', wagtail.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))]))], blank=True),
        ),
    ]
