# Generated by Django 5.0.6 on 2024-06-26 11:33

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0005_alter_idechome_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='idechome',
            name='about',
            field=wagtail.fields.StreamField([('main_info', wagtail.blocks.StructBlock([('main_text', wagtail.blocks.TextBlock()), ('description', wagtail.blocks.TextBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('intro_with_background', wagtail.blocks.StructBlock([('background_text', wagtail.blocks.TextBlock()), ('main_text', wagtail.blocks.TextBlock()), ('brief', wagtail.blocks.TextBlock())]))], blank=True),
        ),
    ]
