# Generated by Django 5.0.6 on 2024-07-02 08:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0011_projectgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='sub_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
