# Generated by Django 5.0.6 on 2024-07-01 09:24

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0011_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='branch',
            field=wagtail.fields.StreamField([('branch_name', wagtail.blocks.CharBlock())], blank=True),
        ),
    ]
