# Generated by Django 5.0.6 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0012_projectindexpage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectindexpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
