# Generated by Django 5.0.6 on 2024-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0013_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='branch',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='company_name',
            field=models.TextField(default='IDEC'),
            preserve_default=False,
        ),
    ]
