# Generated by Django 5.0.6 on 2024-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0014_remove_navigationsettings_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='company_name',
            field=models.TextField(default='IDEC'),
        ),
    ]
