# Generated by Django 5.0.6 on 2024-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0015_alter_navigationsettings_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsettings',
            old_name='mastodon_url',
            new_name='instagram_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='fb_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Linkedin URL'),
        ),
    ]
