# Generated by Django 5.0.6 on 2024-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0015_projectdetailpage_all_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetailpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
