# Generated by Django 5.0.6 on 2024-07-02 14:57

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idec', '0028_alter_idechome_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idechome',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('slider', wagtail.blocks.StreamBlock([('slide', wagtail.blocks.StructBlock([('catchy_text', wagtail.blocks.TextBlock()), ('text', wagtail.blocks.TextBlock()), ('dachedText', wagtail.blocks.TextBlock()), ('buttonText', wagtail.blocks.TextBlock()), ('buttonUrl', wagtail.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))])), ('about', wagtail.blocks.StreamBlock([('main_info', wagtail.blocks.StreamBlock([('main_info_member', wagtail.blocks.StructBlock([('main_text', wagtail.blocks.TextBlock()), ('description', wagtail.blocks.TextBlock())]))])), ('intro_with_background', wagtail.blocks.StructBlock([('background_text', wagtail.blocks.TextBlock()), ('main_text', wagtail.blocks.TextBlock()), ('brief', wagtail.blocks.TextBlock())]))])), ('projects', wagtail.blocks.StreamBlock([('project', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.RichTextBlock()), ('start_date', wagtail.blocks.DateTimeBlock()), ('end_date', wagtail.blocks.DateTimeBlock()), ('clients', wagtail.blocks.CharBlock(max_length=200, required=False)), ('area', wagtail.blocks.CharBlock(max_length=100, required=False)), ('project_year', wagtail.blocks.CharBlock(max_length=4, required=False)), ('project_type', wagtail.blocks.CharBlock(max_length=100, required=False)), ('detail_page', wagtail.blocks.PageChooserBlock(page_type=['idec.ProjectDetailPage'], required=False))]))])), ('feedback', wagtail.blocks.StreamBlock([('feedback', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('rate', wagtail.blocks.CharBlock(max_length=200, required=False)), ('icon', wagtail.blocks.CharBlock(max_length=200, required=False))]))])), ('aboutvideo', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('subtitle', wagtail.blocks.CharBlock(max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.CharBlock(max_length=200, required=False)), ('button', wagtail.blocks.CharBlock(max_length=200, required=False))])), ('services', wagtail.blocks.StreamBlock([('service', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('rate', wagtail.blocks.CharBlock(max_length=200, required=False)), ('icon', wagtail.blocks.CharBlock(max_length=200, required=False))]))]))], blank=True),
        ),
    ]
