# Generated by Django 5.0.6 on 2024-12-04 07:18

import django.db.models.deletion
import modelcluster.fields
import product.models.models
import wagtail.blocks
import wagtail.contrib.forms.models
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '__first__'),
        ('categorization', '__first__'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='productIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('product_intro', models.CharField(blank=True, max_length=255)),
                ('product_sub_title', models.CharField(blank=True, max_length=255)),
                ('product_background', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('banners', wagtail.blocks.StructBlock([('title_b', wagtail.blocks.CharBlock(max_length=100, required=True)), ('subtitle_b', wagtail.blocks.TextBlock(max_length=200, required=False)), ('image_b', wagtail.images.blocks.ImageChooserBlock()), ('link_b', wagtail.blocks.CharBlock(max_length=200, required=False)), ('button_b', wagtail.blocks.CharBlock(max_length=200, required=False))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='categorization.categorymp', validators=[product.models.models.validate_category_level])),
            ],
        ),
        migrations.CreateModel(
            name='productDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('product_title', models.CharField(max_length=255)),
                ('product_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', wagtail.fields.RichTextField(blank=True)),
                ('product_smalldescription', wagtail.fields.RichTextField(blank=True)),
                ('product_details', wagtail.fields.RichTextField(blank=True)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('productContenet', wagtail.blocks.StreamBlock([('product', wagtail.blocks.PageChooserBlock(page_type=['product.productDetailPage'], required=True))])), ('intro_with_background_', wagtail.blocks.StructBlock([('background_text', wagtail.blocks.TextBlock()), ('main_text', wagtail.blocks.TextBlock()), ('brief', wagtail.blocks.TextBlock(required=False)), ('link', wagtail.blocks.PageChooserBlock(page_type=[], required=False)), ('button_all', wagtail.blocks.TextBlock(required=False)), ('link_button_all', wagtail.blocks.TextBlock(required=False))])), ('blogsContenet', wagtail.blocks.StreamBlock([('blog', wagtail.blocks.PageChooserBlock(page_type=['blog.BlogDetailPage'], required=True))]))], blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_page', to='product.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='productGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images_product', to='product.productdetailpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
