# Generated by Django 5.0.6 on 2024-12-15 09:33

import product.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internalCode',
            field=models.CharField(default=product.models.models.get_default_uuid, max_length=50, null=True),
        ),
    ]
