# Generated by Django 5.0.6 on 2024-12-15 09:33

import product.models.models
from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("product", "Product")
    for row in MyModel.objects.all():
        row.internalCode = uuid.uuid4()
        row.save(update_fields=["internalCode"])


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_internalcode'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='internalCode',
            field=models.CharField(default=product.models.models.get_default_uuid, max_length=50, null=True, unique=True),
        ),
    ]
